# Generated by Django 3.1.1 on 2020-10-21 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_weather'),
    ]

    operations = [
        migrations.AddField(
            model_name='weather',
            name='wind_direction',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='weather',
            name='wind_speed',
            field=models.IntegerField(default=0),
        ),
    ]
