# Generated by Django 3.1.1 on 2020-10-21 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_auto_20201021_1357'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weather',
            name='wind_speed',
            field=models.FloatField(default=0),
        ),
    ]
